/*
 * defaultSpecialProvisions.js — The firm's STANDARD Special Provisions text.
 *
 * This is the default that pre-fills the Special Provisions text area on the
 * form. Staff may edit it per client before generating; whatever is submitted
 * is what goes into the document. To change the firm-wide default, edit the
 * string below (this is the single place it lives).
 *
 * Text reproduced verbatim from the firm's POA Long Form. Line breaks are
 * significant — the document engine renders them with linebreaks enabled.
 */
'use strict';

const DEFAULT_SPECIAL_PROVISIONS = `In addition to the powers granted above, I grant my agent the power to act on my behalf with respect to the following subjects.  To the extent a power granted in these SPECIAL PROVISIONS conflicts with an act forbidden by the OPTIONAL ESTATE PLANNING POWERS above, the power granted below controls.
1)	Options and elections related to any annuity, IRA, 401(k) plan, or any other retirement or savings plan, including the power to withdraw or take distribution from any such annuity, account, or plan If I become married and my spouse is a participant in a Qualified Plan or Individual Retirement Account, I authorize my Agent to effect any waiver of my rights to any portion of said Plan or to any payout arrangement which may require my consent or approval by law, under any such Plan, or otherwise.;
2)	Collection of debts;
3)	Charitable pledges and donations;
4)	My Agent may enter any safe-deposit box or other place of safekeeping standing in my name alone or jointly with another and to remove the contents and to make additions.
5)	To transfer any property of mine to the Trustee of any trust for my primary benefit during my lifetime or the benefits of others. With respect to any trust created by me or on my behalf, my Agent may amend, modify, revoke, or terminate the trust.  Further, my Agent may add property to an existing or subsequently created trust, and accept transfers or distributions from any trustee of any trust, including any trust over which I have a right of receipt or withdrawal, whether as grantor, beneficiary, or otherwise.
6)	To deal with current and former employers regarding benefits or any other matters, including changing or designating beneficiary;
7)	Also, and without limiting the authority granted to my Agent in this Section, my Agent may:
(i)	create and fund a sole-benefit trust in accordance with United States Code, Title 42, Section 1396p(c)(2)(B);
(ii)	create and fund a self-settled special needs trust in accordance with United States Code, Title 42, Section 1396p(d)(4)(A);
(iii)	create and fund a qualified income trust in accordance with United States Code, Title 42, Section 1396p(d)(4)(B) if such a trust should be deemed necessary to qualify me for Medicaid benefits, and make arrangements for the diversion of my income to such a trust as necessary to comply with applicable Medicaid rules and regulations; and
(iv)	sign all necessary documents to allow me to join any trust qualifying under United States Code, Title 42, Section 1396p(d)(4)(C) and transfer any portion of my assets to such trust.
8)	To make gifts in addition to or in excess of gifts authorized by and transfer property to my spouse and issue, in any amounts, proportions and manner, including by way of signing and delivering on my behalf any deed or other instrument of conveyance covering any or all of my personal or real property in which I may from time to time have an interest, including, without limitation, the following actions: (1) transfer by gift in advancement of a bequest or devise; (2) release of any life interest, or waiver, renunciation, or declination of any gift to me by will or deed; (3) changing the ownership or beneficiary designations on any annuity, I.R.A., 401 (k) plan, or any other retirement or savings plan; (4) execution of revocable and irrevocable inter vivos trusts on my behalf, and/or amendment of any trust established by me, and transfer of any property of mine to any such trust; and (5) forgiveness of debts. This power includes the ability of the attorney in fact to make gifts to himself/herself, as my attorney-in-fact shall deem appropriate. Such gifts to himself/herself shall not constitute self-dealing or breach of fiduciary duty.

If I become married, my Agent may make, join, and consent to gifts by my spouse pursuant to Section 2513 of the Internal Revenue Code, even if such gifts exceed my aggregate annual gift tax exclusion amount under Section 2503(b) of the Internal Revenue Code.
9)	My Agent may change or maintain my domicile and/or residency for any and all purposes and take any and all actions to effectuate the foregoing.
10)	My Agent, and any successor Agent appointed in this power of attorney, shall have the power and authority of a designated representative for all purposes under the Health Insurance Portability and Accountability Act of 1996 (“HIPAA”), 42 U.S.C. Section 1320d and 45 C.F.R. Parts 160-164.  My Agent and successor Agent are authorized to execute releases and other documents necessary to obtain disclosure of individually identifiable health information, medical records, and patient files, including psychotherapy notes.  This information includes, but is not limited to, any written opinion or assessment of my decision-making capacity.  This authorization and release apply to all information protected by HIPAA and shall only expire if I revoke this power of attorney.
11)	My Agent may reimburse my Health Care Representative under any health care directive, including but not limited to an Advance Healthcare Directive, even if such Health Care Representative is my Agent, for any costs (including legal fees) reasonably incurred in or as a result of acting pursuant to such health care directive.
12)	My Agent may retain, discharge, and pay for, in the sole discretion of my Agent, the services of professionals, including, but not limited to, information technology experts, attorneys, accountants, financial planners, geriatric care managers, social workers, and any other health care professionals.  My Agent is not obligated to retain or pay for any health care professional on my behalf.
13)	If I become married, my Agent may enter into, modify, or amend any pre-nuptial or post-nuptial agreement to which I am or hereafter become a party.  If a named Agent is my spouse, then this power of attorney as to that named Agent is automatically revoked, and that Agent is deemed to have resigned as Agent upon the filing of any separation or dissolution action between us.
14)	Without limiting any other provision of this power of attorney, and subject to the limitations of any other provision of this power of attorney, my Agent has the powers described in this Section.
My Agent has full authority to deal with Online Accounts, Digital Assets, and Digital Devices of all kinds, wherever located.  This authority includes, but is not limited to, the power to acquire, create, establish, access, control, modify, cancel, delete, continue, transfer, and take possession of such accounts, assets, and devices.
However, if I have used an online tool to direct the custodian of an Online Account, Digital Asset, or Digital Device to not disclose certain information, and if the online tool allows for the modification or deletion of that direction at all times, then such direction overrides the authority granted in this Section.
My Agent may request and change my access credentials to any Online Account, Digital Asset, and Digital Device (such as username, password, and secret question), and any third-party dealing with my Agent in good faith will be held harmless for releasing such access credentials.
For purposes of this power of attorney, the following definitions apply:
(1)	Online Accounts
The term “Online Accounts” means accounts that are accessible through the Internet or other similar method, including, but not limited to: bank accounts; investment accounts; other financial accounts; accounts with health care providers;     social media accounts (like LinkedIn, Facebook, and Twitter); gambling and poker accounts; accounts with publishers; accounts for access to employee benefits; email accounts; accounts with Internet service providers; accounts to manage websites and website domain names; accounts with retail vendors; tax-preparation service accounts; affiliate marketing accounts; accounts with utility companies; user access accounts on third-party Digital Devices; and any other online account.
(2)	Digital Assets
The term “Digital Assets” means intangible personal property related to digital technology (whether located on a Digital Device or an Online Account), including, but not limited to: emails sent or received; text messages sent or received; other digital communications sent or received; digital music; digital photographs; digital videos; software licenses; social network accounts; file sharing accounts; online access to financial accounts; domain registrations; DNS service accounts; website hosting accounts; personal and commercial websites; tax preparation service accounts; online store accounts; affiliate marketing accounts; and other types of online accounts and digital items that currently exist or may exist as technology develops.
(3)	Digital Devices
The term “Digital Devices” means tangible personal property related to digital technology capable of storing Digital Assets or accessing Online Accounts, and includes, but is not limited to: desktop computers; laptop computers; tablet computing devices (tablets); other mobile computing devices; peripheral devices; hard disk drives; solid state drives; flash memory devices; other storage devices; mobile telephones; smartphones; and any other type of digital device that currently exists or may exist as technology develops.
15)	My Agent may make reasonable expenditures for the care, maintenance, support, and general welfare of my domestic pets, if any.  Specifically, and without limitation, my Agent may consent to and make reasonable expenditures for medical treatment, boarding, and kennel care of any of my domestic pets.  I authorize any and all payments from my funds for pet care provided by any person or entity, including my Agent.
In addition, my Agent may acquire a domestic service pet if, in my Agent’s sole discretion, such service pet will benefit me.
16)	If my Agent is a professional (such as an attorney; accountant; geriatric care manager; professional guardian, conservator, or other fiduciary; or other professional, including entities that provide similar services), my Agent is entitled to compensation for services rendered pursuant to this power of attorney at such professional’s then stated rates.  If my Agent is not a professional, my Agent is entitled to such compensation at a reasonable rate under the circumstances.
Whether or not my Agent is a professional, my Agent is entitled to reimbursement for costs reasonably incurred while acting as my Agent, including, but not limited to: phone bills; postage; and travel expenses, if necessary, to supervise my care.
17)	My Agent may commence enforcement proceedings, at my expense, against any bank, savings and loan association, credit union, financial institution, brokerage firm, stock transfer agent, insurance company, title insurance company, or other person or entity that fails or refuses to honor this durable power of attorney.;
18)	My Agent may engage in estate and long-term care planning in furtherance of achieving asset preservation.  Property transfers made pursuant to the authority granted herein may be made without restriction as to the value of the transfer, and shall, for all purposes, be deemed to have been “in my best interest” if: (1) made in accordance with the provisions of this section; and (2) made in the context of estate planning, financial planning, Medicaid planning, long term care planning, or asset preservation planning pursuant to the recommendations of an attorney-at-law experienced in such matters.  My Agent may engage in such planning based on all relevant factors, including:
(i)	the value and nature of my property;
(ii)	my foreseeable obligations and need for maintenance;
(iii)	minimization of taxes, including income, estate, inheritance, generation skipping transfer, and gift taxes; and
(iv)	eligibility for a benefit, a program, or assistance under a statute or government regulation.
19)	My Agent may take any action necessary to effectuate the foregoing, including to qualify me for Social Security Benefits, Supplemental Security Income, Veterans Benefits, Medicaid or any other government benefit program.  Such actions may include but shall not be limited to the following:
(i)	convert non-exempt resources into exempt resources;
(ii)	divest me of assets, without restriction as to the value of the divestment;
(iii)	if I become married and my Agent is my spouse, my spouse may protect our assets, whether owned by me alone, my spouse alone, or by us together as husband and wife, so that my spouse’s impoverishment because of my health care costs can be avoided, by whatever lawful methods that might be available;
(iv)	sign a Spousal Refusal (if I become married, and even if my Agent is my spouse);
(v)	sign an Assignment of Support (if I become married, and even if my Agent is my spouse);
(vi)	if I become married, divide community property assets equally or unequally between my spouse and me, without restriction as to the difference of the value of our shares, if any;
(vii)	sign an application for Medical Assistance or any other government benefit program;
(viii)	serve as representative payee;
(ix)	if I become married, transfer the family residence to a spouse who does not need long-term health or nursing care, without restriction as to the value of the transfer;
(x)	make home improvements and additions to my family residence;
(xi)	pay off, partly or in full, any encumbrance on my family residence;
(xii)	purchase a family residence, if I do not own a family residence;
(xiii)	purchase a more expensive family residence; and
(xiv)	attend and represent me at Fair Hearings.
20)	To the extent permitted by law, I hereby expressly grant to my Agent the power to open, contribute to, fund, roll-over, transact with, and/or close an ABLE (Achieving a Better Life Experience) Account in any state, irrespective of whether said account is created by me and is for my benefit, or whether such account is created by and/or for the benefit of another individual.
21)	I specifically authorize my Agent to act as my Representative Payee for Social Security benefits purposes, as authorized by Section 201 of the Strengthening Protections for Social Security Act of 2018, adding new section 42 U.S.C. § 405(j)(l)c. This shall apply to each of the people I have appointed my Agent under this instrument, in the order of priority by which they are listed at the beginning of this instrument.`;

module.exports = { DEFAULT_SPECIAL_PROVISIONS };
